### PR TITLE
162 reaudit step not working

### LINKED ISSUE #162: Reaudit step not working
The reaudit step seems to be throwing errors. Find out if this is also the case in cdos/master and, if not, when the bug was introduced.

### PR DESCRIPTION
**Pull request by vteague**
This fixes two bugs in the reaudit phase, both of which caused nullpointer exceptions. It also adds some tests for proper functioning of various IRV reaudit attempts.

### CODE REVIEW

File: server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java [hunk 1]
```diff
@@ -232,13 +232,14 @@ public static boolean reaudit(final CountyDashboard cdb,
                                 final String comment) {
 
     LOGGER.info("[reaudit] cvr: " + cvr.toString());
-    final CVRAuditInfo cai =
-      Persistence.getByID(cvr.id(), CVRAuditInfo.class);
-    final CastVoteRecord oldAcvr = cai.acvr();
-    if (null == oldAcvr) {
+
```
Comment (michelleblom) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java:235]: We could perhaps use DD or Democracy Developers rather than individual initials?

File: server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java [hunk 2]
```diff
@@ -338,8 +405,11 @@ public void initMocks() {
    * 3. a blank IRV vote,
    * 4. a vote with non-IRV choices ("Alice" instead of "Alice(1)"),
    * 5. a vote with invalid choices (names not in the list of choices for the contest),
-   * 6. a vote that doesn't properly correspond to the IDs it should have, and
-   * 7. an unparseable vote (typos in json data).
+   * 6. a vote that doesn't properly correspond to the IDs it should have,
+   * 7. an unparseable vote (typos in json data),
```
Comment (michelleblom) [inline server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java:409]: Typo: "market" -> "marked"

File: server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java [hunk 3]
```diff
@@ -386,19 +456,35 @@ void testACVRUploadAndStorage() {
...
       // Sixth test: upload a vote with IDs that do not correspond properly to the expected CVR.
       // This should cause an error.
-      testErrorResponse(240514L, IRVWithInconsistentIDsAsJson, malformedACVRMsg);
+      testErrorResponseAndNoMatchingCvr(240514L, IRVWithInconsistentIDsAsJson, malformedACVRMsg);
 
       // Seventh test: upload a vote that has typos preventing json deserialization. This should
       // cause an error.
-      testErrorResponse(240515L, IRVJsonDeserializationFail, malformedACVRMsg);
+      testErrorResponseAndNoMatchingCvr(240515L, IRVJsonDeserializationFail, malformedACVRMsg);
+
```
Comment (michelleblom) [inline server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java:472]: reaudited ballot

File: server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java [hunk 4]
```diff
@@ -386,19 +456,35 @@ void testACVRUploadAndStorage() {
...
+      // Eighth test: upload a reaudit ballot.
+      // Check that the new data successfully replaces the prior upload.
+      testSuccessResponse(240509L, "1-1-1", validIRVReauditAsJson, List.of("Alice","Chuan"), 3);
+      // Test that the previous upload, with a vote for Bob and Chuan (validIRVAsJson) is now tagged as REAUDITED.
+      testPreviousAreReaudited(240509L, "1-1-1", List.of("Bob","Chuan"), 1, 1);
+
```
Comment (michelleblom) [inline server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java:479]: "same ballot being reaudited" ?

File: server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java [hunk 5]
```diff
@@ -456,14 +542,50 @@ private void testSuccessResponse(final long CvrId, final String expectedImprinte
...
+    // Check for the expected number of Reaudited ballots of the required CvrId.
+    final List<CastVoteRecord> acvrs = CastVoteRecordQueries.getMatching(1L, REAUDITED).filter(a -> a.getCvrId() == CvrId).toList();
+    assertEquals(acvrs.size(), expectedReauditedBallots);
+
+    // Check that we have the right records: Imprinted ID should match.
+    assertTrue(acvrs.stream().allMatch(cvr -> cvr.imprintedID().equals(expectedImprintedId)));
+
+    // Find the maximum revision; check that it matches the expected maximum revision (this should match the number of
+    // reaudits).
```
Comment (michelleblom) [inline server/eclipse-project/src/test/java/au/org/democracydevelopers/corla/endpoint/ACVRUploadTests.java:570]: Minor point: can maxRevision or maxRevisionAcvrs be final?

**Review by michelleblom — APPROVED** [review]
